In [19]:
import http.client
import json

conn = http.client.HTTPSConnection("api.collectapi.com")

headers = {
    'content-type': "application/json",
    'authorization': "apikey 5q3wWoOvVBnUsiFatLXzOR:634M26w8HB7UEVPCWgT7Sb"
    }

conn.request("GET", "/gasPrice/stateUsaPrice?state=WA", headers=headers)

res = conn.getresponse()
data = res.read()

# Convert bytes -> Python dictionary
data = json.loads(data.decode("utf-8"))
print(data.keys())

dict_keys(['success', 'result'])

In [20]:
print(data["result"])

{'state': [{'currency': 'usd', 'name': 'Washington', 'lowername': 'washington', 'gasoline': '5.5670', 'midGrade': '5.8530', 'premium': '6.1020', 'diesel': '6.5330'}], 'cities': [{'currency': 'usd', 'gasoline': '5.4760', 'midGrade': '5.7350', 'premium': '5.9010', 'diesel': '6.2200', 'name': 'Bellingham', 'lowername': 'bellingham'}, {'currency': 'usd', 'gasoline': '5.7290', 'midGrade': '6.0120', 'premium': '6.2320', 'diesel': '6.5530', 'name': 'Bremerton', 'lowername': 'bremerton'}, {'currency': 'usd', 'gasoline': '5.5370', 'midGrade': '5.7600', 'premium': '6.0650', 'diesel': '6.7290', 'name': 'Olympia', 'lowername': 'olympia'}, {'currency': 'usd', 'gasoline': '5.1990', 'midGrade': '5.4900', 'premium': '5.7680', 'diesel': '6.2060', 'name': 'Richland-Kennewick-Pasco', 'lowername': 'richland-kennewick-pasco'}, {'currency': 'usd', 'gasoline': '5.8330', 'midGrade': '6.0830', 'premium': '6.3260', 'diesel': '6.8040', 'name': 'Seattle-Bellevue-Everett', 'lowername': 'seattle-bellevue-everett'}, {'currency': 'usd', 'gasoline': '5.1100', 'midGrade': '5.3980', 'premium': '5.6410', 'diesel': '6.1920', 'name': 'Spokane', 'lowername': 'spokane'}, {'currency': 'usd', 'gasoline': '5.6890', 'midGrade': '5.9360', 'premium': '6.1730', 'diesel': '6.6900', 'name': 'Tacoma', 'lowername': 'tacoma'}, {'currency': 'usd', 'gasoline': '5.3290', 'midGrade': '5.6520', 'premium': '5.8880', 'diesel': '6.3260', 'name': 'Yakima', 'lowername': 'yakima'}, {'currency': 'usd', 'gasoline': '5.4920', 'midGrade': '5.7450', 'premium': '5.9950', 'diesel': '6.3470', 'name': 'Vancouver', 'lowername': 'vancouver'}, {'currency': 'usd', 'gasoline': '4.8160', 'midGrade': '5.3490', 'premium': '5.5560', 'diesel': '5.9840', 'name': 'Clarkson', 'lowername': 'clarkson'}, {'currency': 'usd', 'gasoline': '5.5090', 'midGrade': '5.7670', 'premium': '6.0320', 'diesel': '6.4730', 'name': 'Longview', 'lowername': 'longview'}, {'currency': 'usd', 'gasoline': '5.4250', 'midGrade': '5.6460', 'premium': '5.9070', 'diesel': '6.3260', 'name': 'Mount Vernon-Anacortes', 'lowername': 'mount vernon-anacortes'}, {'currency': 'usd', 'gasoline': '5.4020', 'midGrade': '5.6290', 'premium': '5.9820', 'diesel': '6.6010', 'name': 'Walla Walla', 'lowername': 'walla walla'}, {'currency': 'usd', 'gasoline': '5.1960', 'midGrade': '5.3910', 'premium': '5.6780', 'diesel': '6.2760', 'name': 'Wenatchee', 'lowername': 'wenatchee'}]}

In [21]:
cities = data["result"]["cities"]

print(cities)

[{'currency': 'usd', 'gasoline': '5.4760', 'midGrade': '5.7350', 'premium': '5.9010', 'diesel': '6.2200', 'name': 'Bellingham', 'lowername': 'bellingham'}, {'currency': 'usd', 'gasoline': '5.7290', 'midGrade': '6.0120', 'premium': '6.2320', 'diesel': '6.5530', 'name': 'Bremerton', 'lowername': 'bremerton'}, {'currency': 'usd', 'gasoline': '5.5370', 'midGrade': '5.7600', 'premium': '6.0650', 'diesel': '6.7290', 'name': 'Olympia', 'lowername': 'olympia'}, {'currency': 'usd', 'gasoline': '5.1990', 'midGrade': '5.4900', 'premium': '5.7680', 'diesel': '6.2060', 'name': 'Richland-Kennewick-Pasco', 'lowername': 'richland-kennewick-pasco'}, {'currency': 'usd', 'gasoline': '5.8330', 'midGrade': '6.0830', 'premium': '6.3260', 'diesel': '6.8040', 'name': 'Seattle-Bellevue-Everett', 'lowername': 'seattle-bellevue-everett'}, {'currency': 'usd', 'gasoline': '5.1100', 'midGrade': '5.3980', 'premium': '5.6410', 'diesel': '6.1920', 'name': 'Spokane', 'lowername': 'spokane'}, {'currency': 'usd', 'gasoline': '5.6890', 'midGrade': '5.9360', 'premium': '6.1730', 'diesel': '6.6900', 'name': 'Tacoma', 'lowername': 'tacoma'}, {'currency': 'usd', 'gasoline': '5.3290', 'midGrade': '5.6520', 'premium': '5.8880', 'diesel': '6.3260', 'name': 'Yakima', 'lowername': 'yakima'}, {'currency': 'usd', 'gasoline': '5.4920', 'midGrade': '5.7450', 'premium': '5.9950', 'diesel': '6.3470', 'name': 'Vancouver', 'lowername': 'vancouver'}, {'currency': 'usd', 'gasoline': '4.8160', 'midGrade': '5.3490', 'premium': '5.5560', 'diesel': '5.9840', 'name': 'Clarkson', 'lowername': 'clarkson'}, {'currency': 'usd', 'gasoline': '5.5090', 'midGrade': '5.7670', 'premium': '6.0320', 'diesel': '6.4730', 'name': 'Longview', 'lowername': 'longview'}, {'currency': 'usd', 'gasoline': '5.4250', 'midGrade': '5.6460', 'premium': '5.9070', 'diesel': '6.3260', 'name': 'Mount Vernon-Anacortes', 'lowername': 'mount vernon-anacortes'}, {'currency': 'usd', 'gasoline': '5.4020', 'midGrade': '5.6290', 'premium': '5.9820', 'diesel': '6.6010', 'name': 'Walla Walla', 'lowername': 'walla walla'}, {'currency': 'usd', 'gasoline': '5.1960', 'midGrade': '5.3910', 'premium': '5.6780', 'diesel': '6.2760', 'name': 'Wenatchee', 'lowername': 'wenatchee'}]

In [22]:
import pandas as pd

cities_df = pd.DataFrame(cities)
cities_df.head()

,currency,gasoline,midGrade,premium,diesel,name,lowername
0,usd,5.4760,5.7350,5.9010,6.2200,Bellingham,bellingham
1,usd,5.7290,6.0120,6.2320,6.5530,Bremerton,bremerton
2,usd,5.5370,5.7600,6.0650,6.7290,Olympia,olympia
3,usd,5.1990,5.4900,5.7680,6.2060,Richland-Kennewick-Pasco,richland-kennewick-pasco
4,usd,5.8330,6.0830,6.3260,6.8040,Seattle-Bellevue-Everett,seattle-bellevue-everett

In [23]:
cities_df = cities_df.drop(columns='lowername')
cities_df.head()

  currency gasoline midGrade premium  diesel                      name
0      usd   5.4760   5.7350  5.9010  6.2200                Bellingham
1      usd   5.7290   6.0120  6.2320  6.5530                 Bremerton
2      usd   5.5370   5.7600  6.0650  6.7290                   Olympia
3      usd   5.1990   5.4900  5.7680  6.2060  Richland-Kennewick-Pasco
4      usd   5.8330   6.0830  6.3260  6.8040  Seattle-Bellevue-Everett

In [24]:
cities_df = cities_df.rename(columns={'name':'cities'})
cities_df

   currency gasoline midGrade premium  diesel                    cities
0       usd   5.4760   5.7350  5.9010  6.2200                Bellingham
1       usd   5.7290   6.0120  6.2320  6.5530                 Bremerton
2       usd   5.5370   5.7600  6.0650  6.7290                   Olympia
3       usd   5.1990   5.4900  5.7680  6.2060  Richland-Kennewick-Pasco
4       usd   5.8330   6.0830  6.3260  6.8040  Seattle-Bellevue-Everett
5       usd   5.1100   5.3980  5.6410  6.1920                   Spokane
6       usd   5.6890   5.9360  6.1730  6.6900                    Tacoma
7       usd   5.3290   5.6520  5.8880  6.3260                    Yakima
8       usd   5.4920   5.7450  5.9950  6.3470                 Vancouver
9       usd   4.8160   5.3490  5.5560  5.9840                  Clarkson
10      usd   5.5090   5.7670  6.0320  6.4730                  Longview
11      usd   5.4250   5.6460  5.9070  6.3260    Mount Vernon-Anacortes
12      usd   5.4020   5.6290  5.9820  6.6010               Walla Walla
13      usd   5.1960   5.3910  5.6780  6.2760                 Wenatchee

In [25]:
from sqlalchemy import create_engine , text
import psycopg2

DATABASE_NAME = 'postgres'
DATABASE_USER = 'postgres'
DATABASE_PORT = 5432
DATABASE_PASSWORD = 'russwizi'
DATABASE_HOST= 'localhost'

engine = create_engine(f'postgresql+psycopg2://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}')

In [17]:
with engine.connect() as conn:
    resort = conn.execute(text('select 1;'))
    for i in resort:
        print(i)

(1,)

WARNING:  database "postgres" has a collation version mismatch
DETAIL:  The database was created using collation version 2.41, but the operating system provides version 2.42.
HINT:  Rebuild all objects in this database that use the default collation and run ALTER DATABASE postgres REFRESH COLLATION VERSION, or build PostgreSQL with the right library version.

In [18]:
cities_df.to_sql('cities',engine, if_exists='replace', index= False)

14